# See LICENSE for license details.
base_dir := $(patsubst %/,%,$(dir $(abspath $(lastword $(MAKEFILE_LIST)))))
BUILD_DIR := $(base_dir)/builds/vc707-u500devkit
FPGA_DIR := $(base_dir)/fpga-shells/xilinx
PROJECT := sifive.fpgashells.shell.xilinx
MODEL := VC707Shell
export CONFIG_PROJECT := sifive.freedom.unleashed
export CONFIG := DevKitU500FPGADesign_WithDevKit150MHz
export BOARD := vc707
export BOOTROM_DIR := $(base_dir)/bootrom/freedom-u540-c000-bootloader
export keystone := yes
export pcie := no
KEYSTONE_ACC_DIR := $(base_dir)/keystone-acc
SHA3_DIR := $(KEYSTONE_ACC_DIR)/vsrc/sha3
SHA3_HIGHPERF_DIR := $(SHA3_DIR)/trunk/high_throughput_core

rocketchip_dir := $(base_dir)/rocket-chip
sifiveblocks_dir := $(base_dir)/sifive-blocks
VSRCS := \
	$(rocketchip_dir)/src/main/resources/vsrc/AsyncResetReg.v \
	$(rocketchip_dir)/src/main/resources/vsrc/plusarg_reader.v \
	$(sifiveblocks_dir)/vsrc/SRLatch.v \
	$(FPGA_DIR)/common/vsrc/PowerOnResetFPGAOnly.v \
	$(FPGA_DIR)/$(BOARD)/vsrc/sdio.v \
	$(FPGA_DIR)/$(BOARD)/vsrc/vc707reset.v \
	$(BUILD_DIR)/$(CONFIG_PROJECT).$(CONFIG).rom.v \
	$(BUILD_DIR)/$(CONFIG_PROJECT).$(CONFIG).v \
	$(SHA3_HIGHPERF_DIR)/rtl/f_permutation.v \
	$(SHA3_HIGHPERF_DIR)/rtl/round2in1.v \
	$(SHA3_HIGHPERF_DIR)/rtl/padder1.v \
	$(SHA3_HIGHPERF_DIR)/rtl/keccak.v \
	$(SHA3_HIGHPERF_DIR)/rtl/padder.v \
	$(SHA3_HIGHPERF_DIR)/rtl/rconst2in1.v

include common.mk
