# See LICENSE for license details.
base_dir := $(patsubst %/,%,$(dir $(abspath $(lastword $(MAKEFILE_LIST)))))
BUILD_DIR := $(base_dir)/builds/vc707-u500devkit-keystone
FPGA_DIR := $(base_dir)/fpga-shells/xilinx
PROJECT := uec.keystoneAcc.fpgashells.shell.xilinx
MODEL := VC707Shell
export CONFIG_PROJECT := uec.keystoneAcc.freedom.unleashed
export CONFIG := DevKitU500FPGADesign_WithDevKit150MHz
export BOARD := vc707
export BOOTROM_DIR := $(base_dir)/bootrom/freedom-u540-c000-bootloader
KEYSTONE_ACC_DIR := $(base_dir)/keystone-acc
SHA3_DIR := $(KEYSTONE_ACC_DIR)/vsrc/sha3
SHA3_HIGHPERF_DIR := $(SHA3_DIR)/trunk/high_throughput_core
ED25519_DIR = $(KEYSTONE_ACC_DIR)/vsrc/ed25519

rocketchip_dir := $(base_dir)/rocket-chip
sifiveblocks_dir := $(base_dir)/sifive-blocks
VSRCS := \
	$(rocketchip_dir)/src/main/resources/vsrc/AsyncResetReg.v \
	$(rocketchip_dir)/src/main/resources/vsrc/plusarg_reader.v \
	$(sifiveblocks_dir)/vsrc/SRLatch.v \
	$(FPGA_DIR)/common/vsrc/PowerOnResetFPGAOnly.v \
	$(FPGA_DIR)/$(BOARD)/vsrc/sdio.v \
	$(FPGA_DIR)/$(BOARD)/vsrc/vc707reset.v \
	$(BUILD_DIR)/$(CONFIG_PROJECT).$(CONFIG).rom.v \
	$(BUILD_DIR)/$(CONFIG_PROJECT).$(CONFIG).v \
	$(SHA3_HIGHPERF_DIR)/rtl/f_permutation.v \
	$(SHA3_HIGHPERF_DIR)/rtl/round2in1.v \
	$(SHA3_HIGHPERF_DIR)/rtl/padder1.v \
	$(SHA3_HIGHPERF_DIR)/rtl/keccak.v \
	$(SHA3_HIGHPERF_DIR)/rtl/padder.v \
	$(SHA3_HIGHPERF_DIR)/rtl/rconst2in1.v \
	$(ED25519_DIR)/rtl/mac16_generic.v \
	$(ED25519_DIR)/rtl/ed25519_microcode_rom.v \
	$(ED25519_DIR)/rtl/ed25519_operand_bank.v \
	$(ED25519_DIR)/rtl/adder47_generic.v \
	$(ED25519_DIR)/rtl/ed25519_uop_worker.v \
	$(ED25519_DIR)/rtl/subtractor32_generic.v \
	$(ED25519_DIR)/rtl/ed25519_wrapper.v \
	$(ED25519_DIR)/rtl/ed25519_core_top.v \
	$(ED25519_DIR)/rtl/bram_1rw_1ro_readfirst.v \
	$(ED25519_DIR)/rtl/bram_1rw_readfirst.v \
	$(ED25519_DIR)/rtl/bram_1wo_1ro_readfirst.v \
	$(ED25519_DIR)/rtl/ed25519_base_point_multiplier.v \
	$(ED25519_DIR)/rtl/curve25519_modular_multiplier.v \
	$(ED25519_DIR)/rtl/ed25519_banks_array.v \
	$(ED25519_DIR)/rtl/modular_adder.v \
	$(ED25519_DIR)/rtl/modular_subtractor.v \
	$(ED25519_DIR)/rtl/adder32_generic.v \
	$(ED25519_DIR)/rtl/multiword_mover.v

include common.mk
